// angular/movie-app/src/app/movie-list/movie-filter/movie-filter.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-movie-filter',
  template: `
    <div>
      <nav>
        <div *ngFor="let f of filters">
          <span class="item" [class]="f.key == filter.key ? 'active' : ''"
            (click)="onFilterChange(f)">
              {{f.name}}\
            </span>
        </div>
      </nav>
    </div>
  `,
  styleUrls: ['./movie-filter.component.css']
})
export class MovieFilterComponent {

  @Input()
  filter

  @Input()
  onFilterChange: Function

  filters = [
    {key: 'popular', name: 'Popular'},
    {key: 'now_playing', name: 'Now Playing'},
    {key: 'upcoming', name: 'Upcoming'},
    {key: 'top_rated', name: 'Top Rated'}
  ]
  constructor() { }

}

// react/movie-app/src/components/MovieList/MovieFilter/MovieFilter.js
import React from 'react'
import './MovieFilter.css'

export default function MovieFilter(props) {
  const filters = [
    {key: 'popular', name: 'Popular'},
    {key: 'now_playing', name: 'Now Playing'},
    {key: 'upcoming', name: 'Upcoming'},
    {key: 'top_rated', name: 'Top Rated'}
  ]

  const listFilters = filters.map((filter) => 
    <div key={filter.key}>
      <span 
          className={`item ${filter.key === props.filter.key ? 'active' : ''}`} 
          onClick={() => {props.onFilterChange(filter)}}>
      {filter.name}
      </span>
    </div>
  )
  
  return (
    <div>
      <nav>
        {listFilters}
      </nav>
    </div>
  )
}
