// vue/movie-app/src/components/MovieList/MovieList.vue
<template>
  <div>
    <MovieFilter @filterchange="handleFilterChange" :filter="filter"/>
    <div class="movie-list">
      <div v-for="(movie, index) in movies" :key="movie.id" >
        <div v-if="movies.length == index + 1">
          <MovieCard id="lastMovieCard" :movie="movie" />
        </div>
        <MovieCard v-else :movie="movie" />
      </div>
    </div>
  </div>
</template>

<script>
import MovieCard from './MovieCard/MovieCard';
import MovieFilter from './MovieFilter/MovieFilter';
import * as apiMovies from '../../api/apiMovies';

export default {
  components: {
    MovieFilter,
    MovieCard
  },
  
  computed: {
    watcherFilter() {
      return [this.filter, this.page];
    }
  },

  watch: {
    /**
     * Update the movies if filter or page change
     */
    watcherFilter() {
      this.getMovies();
    },
  },

  data() {
    return {
      movies: [],
      filter: {key: 'popular', name: 'Popular'},

      page: 1,
      hasMore: false,
      loading: true
    }
  },

  methods: {

    /**
     * 
     */
    async getMovies() {
      this.loading = true;
      await apiMovies.getMovies({page: this.page, filter: this.filter.key})
      .then(res => {
        this.movies =  [...this.movies, ...res.data.results];
        this.hasMore = this.page < res.data.total_pages;
        this.loading = false;
      })
    },

    /**
     * 
     */
    handleFilterChange(newFilter) {
      if (this.filter === newFilter)
        return;

      this.filter = newFilter;
      this.movies = [];
      this.page = 1;
    },

    infiniteScroll() {
      if (this.loading) return;

      const node = document.querySelector("#lastMovieCard");

      const observer = new IntersectionObserver(entries => {
        entries.forEach(entry => {
          if (entry.isIntersecting && this.hasMore) {
            console.log('Visible');
            this.page += 1;
          }
        })
      });

      if (node) {
        observer.observe(node);
      }
    }
  },

  beforeMount() {
    this.getMovies();
  },
  mounted() {
    this.$watch('loading', this.infiniteScroll, {immediate: true});
  }
}
</script>

<style>
.movie-list {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  grid-auto-rows: auto;
  grid-gap: 1rem;
  justify-items: center;

  max-width: 90%;
  margin: 0 auto;
}
</style>

// svelte/movie-app/src/components/MovieList/MovieList.svelte
<script>
import { onMount } from 'svelte'

import MovieCard from './MovieCard/MovieCard.svelte'
import MovieFilter from './MovieFilter/MovieFilter.svelte'
import * as apiMovies from '../../api/apiMovies'

  let movies = []
  let filter = {key: 'popular', name: 'Popular'}
  let page = 1
  // let hasMore = false
  let loading = true

  const handleFilterChange = (event) => {
    const newFilter = event.detail
    if (filter === newFilter)
      return
    filter = newFilter
    movies = []
    page = 1

    getMovies()
  }

  async function getMovies(){
    loading = true
    await apiMovies.getMovies({page: page, filter: filter.key})
    .then(res => {
      movies = [...movies, ...res.data.results]
      // hasMore = page < res.data.total_pages
      loading = false
    })
  }

  onMount(async () => {
		getMovies()
  });
  
</script>

<div>
  <MovieFilter filter={filter} on:filterChanged={handleFilterChange}/>
  <div class="movie-list">
    {#each movies as movie }
      <MovieCard movie={movie} />
    {/each}
  </div>
</div>

<style>
.movie-list {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  grid-auto-rows: auto;
  grid-gap: 1rem;
  justify-items: center;

  max-width: 90%;
  margin: 0 auto;
}
</style>
