// svelte/movie-app/src/components/MovieList/MovieList.svelte
<script>
import { onMount } from 'svelte'

import MovieCard from './MovieCard/MovieCard.svelte'
import MovieFilter from './MovieFilter/MovieFilter.svelte'
import * as apiMovies from '../../api/apiMovies'

  let movies = []
  let filter = {key: 'popular', name: 'Popular'}
  let page = 1
  // let hasMore = false
  let loading = true

  const handleFilterChange = (event) => {
    const newFilter = event.detail
    if (filter === newFilter)
      return
    filter = newFilter
    movies = []
    page = 1

    getMovies()
  }

  async function getMovies(){
    loading = true
    await apiMovies.getMovies({page: page, filter: filter.key})
    .then(res => {
      movies = [...movies, ...res.data.results]
      // hasMore = page < res.data.total_pages
      loading = false
    })
  }

  onMount(async () => {
		getMovies()
  });
  
</script>

<div>
  <MovieFilter filter={filter} on:filterChanged={handleFilterChange}/>
  <div class="movie-list">
    {#each movies as movie }
      <MovieCard movie={movie} />
    {/each}
  </div>
</div>

<style>
.movie-list {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  grid-auto-rows: auto;
  grid-gap: 1rem;
  justify-items: center;

  max-width: 90%;
  margin: 0 auto;
}
</style>

// angular/movie-app/src/app/movie-list/movie-list.component.ts
import { Component, OnInit } from '@angular/core';
import * as apiMovies from '../../api/apiMovies'

@Component({
  selector: 'app-movie-list',
  template: `
    <div>
      <app-movie-filter [filter]="filter" (edit)="handleFilterChange($event)"></app-movie-filter>
      <div class="movie-list">
        <div *ngFor="let movie of movies">
          <div><app-movie-card [movie]="movie"></app-movie-card></div>
        </div>
      </div>
    </div>
  `,
  styleUrls: ['./movie-list.component.css']
})

export class MovieListComponent implements OnInit {

  // Data
  movies = []
  filter = {key: 'popular', name: 'Popular'}
  page = 1
  hasMore = false
  loading = true

  async getMovies() {
    this.loading = true;
    await apiMovies.getMovies({page: this.page, filter: this.filter.key})
    .then(res => {
      this.movies =  [...this.movies, ...res.data.results];
      this.hasMore = this.page < res.data.total_pages;
      this.loading = false;
    })
  }

  handleFilterChange(newFilter) {
    if (this.filter === newFilter)
      return
    this.filter = newFilter;
    this.movies = []
    this.page = 1
    
    this.getMovies();
  }

  constructor() { }

  ngOnInit() {
    this.getMovies();
  }
}
