// react/movie-app/src/components/MovieBrowser/MovieList/MovieList.js
import React from 'react'
import * as apiMovies from '../../../api/apiMovies'
import MovieCard from './MovieCard/MovieCard'
import MovieFilter from './MovieFilter/MovieFilter.js'
import './MovieList.css'

export default class MovieList extends React.Component {

  state = {
    movieList: [],
    filter: {
      key: 'popular', name: 'Popular'
    },
    pagination : {
      page: 1,
      total_results: 0,
      total_pages: 0,
    }
  }

  componentDidMount() {
    this.getMovies()
  }

  getMovies = (page) => {
    apiMovies.getMovies({page: this.state.pagination.page, filter: this.state.filter.key}).then(result => {
      this.setState({
        movieList: result.data.results,
        pagination: {
          page: result.data.page,
          total_results: result.data.total_results,
          total_pages: result.data.total_pages,
        }
      })
    })
  }

  onFilterChange = (filter) => {
    if (filter === this.state.filter)
      return
    this.setState({
      filter
    })
    this.getMovies(1)
  }

  render() {
    const list = this.state.movieList.map(movie => 
      <MovieCard movie={movie} key={movie.id}/>
    )

    return (
      <div>
        <MovieFilter onFilterChange={this.onFilterChange} filter={this.state.filter}/>
        <div className="movie-list">
          {list}
        </div>
s      </div>
    )
  }
}

// angular/movie-app/src/app/movie-list/movie-list.component.ts
import { Component, OnInit } from '@angular/core';
import * as apiMovies from '../../api/apiMovies'

@Component({
  selector: 'app-movie-list',
  template: `
    <div>
      <app-movie-filter [filter]="filter" (edit)="handleFilterChange($event)"></app-movie-filter>
      <div class="movie-list">
        <div *ngFor="let movie of movies">
          <div><app-movie-card [movie]="movie"></app-movie-card></div>
        </div>
      </div>
    </div>
  `,
  styleUrls: ['./movie-list.component.css']
})

export class MovieListComponent implements OnInit {

  // Data
  movies = []
  filter = {key: 'popular', name: 'Popular'}
  page = 1
  hasMore = false
  loading = true

  async getMovies() {
    this.loading = true;
    await apiMovies.getMovies({page: this.page, filter: this.filter.key})
    .then(res => {
      this.movies =  [...this.movies, ...res.data.results];
      this.hasMore = this.page < res.data.total_pages;
      this.loading = false;
    })
  }

  handleFilterChange(newFilter) {
    if (this.filter === newFilter)
      return
    this.filter = newFilter;
    this.movies = []
    this.page = 1
    
    this.getMovies();
  }

  constructor() { }

  ngOnInit() {
    this.getMovies();
  }
}
