// react/movie-app/src/components/MovieList/MovieList.js
import React, {useState, useEffect, useRef, useCallback} from 'react';

import * as apiMovies from '../../api/apiMovies';
import MovieCard from './MovieCard/MovieCard';
import MovieFilter from './MovieFilter/MovieFilter.js';
import Bar from '../NavigationBar/Bar';

import './MovieList.css';

export default function MovieList() {

  const [movies, setMovies] = useState([]);
  const [filter, setFilter] = useState({key: 'popular', name: 'Popular'});
  const [page, setPage] = useState(1);
  const [hasMore, setHasMore] = useState(false);
  const [loading, setLoading] = useState(true);

  // Infinity Scroll Filter
  const observer = useRef();
  const lastMovieElementRef = useCallback(node => {
    if (loading) return;
    if (observer.current) {
      observer.current.disconnect();
    }

    // Aply a logic to the observer
    observer.current = new IntersectionObserver(entries => {
      // Just use one entry (observing one node)
      if(entries[0].isIntersecting && hasMore) {
        console.log('Visible');
        setPage(prevPage => prevPage + 1);
      }
    })
    
    // Select the node to oserve 
    if (node) {
      observer.current.observe(node);
    }
  }, [loading]) //Once that the loading change to false, observe a new node

  useEffect((a) => {
    setLoading(true);
    apiMovies.getMovies({page: page, filter: filter.key}).then(res => {
      setMovies(prevMovies => [...prevMovies, ...res.data.results]);
      setHasMore(page < res.data.total_pages);
      setLoading(false);
    });
  }, [filter, page])
  
  function handleFilterChange(newFilter) {
    if (filter === newFilter)
      return;
    
    setFilter(newFilter);
    setMovies([]);
    setPage(1);
  }

  return (
    <div>
      <Bar/>
      <MovieFilter onFilterChange={handleFilterChange} filter={filter}/>
      <div className="movie-list">
        { movies.map((movie, index) => {
          if (index + 1 === movies.length) {
            return <div ref={lastMovieElementRef} key={movie.id}><MovieCard movie={movie} /></div>
          } else {
            return <div key={movie.id}><MovieCard movie={movie} /></div>
          }
        }) }
      </div>
    </div>
  );
}

// vue/movie-app/src/components/MovieList/MovieList.vue
<template>
  <div>
    <Bar/>
    <MovieFilter :onFilterChange="handleFilterChange" :filter="filter"/>
    <div class="movie-list">
      <div v-for="(movie, index) in movies" :key="movie.id" >
        <div v-if="movies.length == index + 1" ref="lastMovieCard">
          <MovieCard id="lastMovieCard" :movie="movie" />
        </div>
        <MovieCard v-else :movie="movie" />
      </div>
    </div>
  </div>
</template>

<script>
import Bar from '../NavigationBar/Bar';
import MovieCard from './MovieCard/MovieCard';
import MovieFilter from './MovieFilter/MovieFilter';
import * as apiMovies from '../../api/apiMovies';

export default {
  components: {
    Bar,
    MovieFilter,
    MovieCard
  },
  
  computed: {
    watcherFilter() {
      return [this.filter, this.page];
    }
  },

  watch: {
    /**
     * Update the movies if filter or page change
     */
    watcherFilter() {
      this.getMovies();
    },
  },

  data() {
    return {
      movies: [],
      filter: {key: 'popular', name: 'Popular'},

      page: 1,
      hasMore: false,
      loading: true
    }
  },

  methods: {

    /**
     * 
     */
    async getMovies() {
      this.loading = true;
      await apiMovies.getMovies({page: this.page, filter: this.filter.key})
      .then(res => {
        this.movies =  [...this.movies, ...res.data.results];
        this.hasMore = this.page < res.data.total_pages;
        this.loading = false;
      })
    },

    /**
     * 
     */
    handleFilterChange(newFilter) {
      if (this.filter === newFilter)
        return;

      this.filter = newFilter;
      this.movies = [];
      this.page = 1;
    },

    infiniteScroll() {
      if (this.loading) return;

      const node = document.querySelector("#lastMovieCard");

      const observer = new IntersectionObserver(entries => {
        entries.forEach(entry => {
          if (entry.isIntersecting && this.hasMore) {
            console.log('Visible');
            this.page += 1;
          }
        })
      });

      if (node) {
        observer.observe(node);
      }
    }
  },

  beforeMount() {
    this.getMovies();
  },
  mounted() {
    this.$watch('loading', this.infiniteScroll, {immediate: true});
  }
}
</script>

<style>
.movie-list {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  grid-auto-rows: auto;
  grid-gap: 1rem;
  justify-items: center;

  max-width: 90%;
  margin: 0 auto;
}
</style>
